

/* First created by JCasGen Wed Sep 11 22:12:28 EDT 2013 */
package hw1.type.input;

import org.apache.uima.jcas.JCas; 
import org.apache.uima.jcas.JCasRegistry;
import org.apache.uima.jcas.cas.TOP_Type;

import hw1.type.General;
import org.apache.uima.jcas.cas.FSList;


/** It combines the NGrams to a NGram list where each NGram in a list is generated by the same answer.</br> In this way, an Answer corresponds to exactly one NGram list.
 * Updated by JCasGen Wed Sep 11 22:12:28 EDT 2013
 * XML source: /home/jerry/git/hw1-chens1/hw1-chens1/src/main/resources/TypeSystem.xml
 * @generated */
public class NGramList extends General {
  /** @generated
   * @ordered 
   */
  @SuppressWarnings ("hiding")
  public final static int typeIndexID = JCasRegistry.register(NGramList.class);
  /** @generated
   * @ordered 
   */
  @SuppressWarnings ("hiding")
  public final static int type = typeIndexID;
  /** @generated  */
  @Override
  public              int getTypeIndexID() {return typeIndexID;}
 
  /** Never called.  Disable default constructor
   * @generated */
  protected NGramList() {/* intentionally empty block */}
    
  /** Internal - constructor used by generator 
   * @generated */
  public NGramList(int addr, TOP_Type type) {
    super(addr, type);
    readObject();
  }
  
  /** @generated */
  public NGramList(JCas jcas) {
    super(jcas);
    readObject();   
  } 

  /** @generated */  
  public NGramList(JCas jcas, int begin, int end) {
    super(jcas);
    setBegin(begin);
    setEnd(end);
    readObject();
  }   

  /** <!-- begin-user-doc -->
    * Write your own initialization here
    * <!-- end-user-doc -->
  @generated modifiable */
  private void readObject() {/*default - does nothing empty block */}
     
 
    
  //*--------------*
  //* Feature: NGrams

  /** getter for NGrams - gets The NGrams contains a list of NGRams. They are all from one answer sentence.
   * @generated */
  public FSList getNGrams() {
    if (NGramList_Type.featOkTst && ((NGramList_Type)jcasType).casFeat_NGrams == null)
      jcasType.jcas.throwFeatMissing("NGrams", "hw1.type.input.NGramList");
    return (FSList)(jcasType.ll_cas.ll_getFSForRef(jcasType.ll_cas.ll_getRefValue(addr, ((NGramList_Type)jcasType).casFeatCode_NGrams)));}
    
  /** setter for NGrams - sets The NGrams contains a list of NGRams. They are all from one answer sentence. 
   * @generated */
  public void setNGrams(FSList v) {
    if (NGramList_Type.featOkTst && ((NGramList_Type)jcasType).casFeat_NGrams == null)
      jcasType.jcas.throwFeatMissing("NGrams", "hw1.type.input.NGramList");
    jcasType.ll_cas.ll_setRefValue(addr, ((NGramList_Type)jcasType).casFeatCode_NGrams, jcasType.ll_cas.ll_getFSRef(v));}    
  }

    